### PR TITLE
Call RequestCreated after request is created

### LINKED ISSUE #379: History service when creating a new project
Save fails:

The INSERT statement conflicted with the FOREIGN KEY constraint "FK_ProjectHistory_Projects_ProjectId". The conflict occurred in database "Harvest", table "dbo.Projects", column 'Id'.
The statement has been terminated.

### PR DESCRIPTION
**Pull request by sprucely**
closes #379

### CODE REVIEW

**Comment by jSylvestre** [comment]
@sprucely I thought @srkirkland didn't like this solution....

**Comment by srkirkland** [comment]
Can't we associate newProject with the history entry in the db and let EF handle the save. Saving twice like this feels like it isn't using EF correctly.

**Comment by jSylvestre** [comment]
Some example code incoming

**Comment by sprucely** [comment]
@srkirkland Now I get it. I'm so used to doing things with PK's that I forget about using navigation properties...

**Comment by jSylvestre** [comment]
Done in other pr...

**Pull request closed without merging**
