### PR TITLE
Add a db project

### PR DESCRIPTION
**Pull request by jSylvestre**

### CODE REVIEW

**Comment by jSylvestre** [comment]
This is the schema from test.
The view is just something I have locally

**Review by srkirkland — APPROVED** [review]
As long as it is set to not build in any configuration.  I can't tell from the sln file if that's the case but if not you should change it.

**Comment by jSylvestre** [comment]
@srkirkland You just mean this correct?
image

**Comment by srkirkland** [comment]
> @srkirkland You just mean this correct?
> image

Correct -- don't build or deploy in any of the configurations for that project

**Pull request merged**
