### PR TITLE
Pass project not Id.

### PR DESCRIPTION
**Pull request by jSylvestre**
I'm sure this could be cleaned up

### CODE REVIEW

**Comment by jSylvestre** [comment]
Possible solution to #379

**Review by sprucely — APPROVED** [review]
Haha. This is what I was going to do. But why name it MakeHistory2 instead of just overloading?

**Comment by jSylvestre** [comment]
> Haha. This is what I was going to do. But why name it MakeHistory2 instead of just overloading?

I didn't see where it was failing originally and was just testing. I'll fix it up.

**Comment by jSylvestre** [comment]
resolves #379

**Review by sprucely — APPROVED** [review]

**Pull request merged**
