### PR TITLE
Added some fancy filtering

### LINKED ISSUE #531: Fancy table filtering
A few other fancy table filters, these will be easier than the date filter one:

- [x] Crop Type filter should just be a dropdown with "Any, Row, Tree" as the options
- [x] Progress filter should be dropdown with "<25%, 25-50%, 50-75%, >75%" as the options.
- [x] Status should be a dropdown with all of the possible statuses, or at least all of the statuses that are in the table

### PR DESCRIPTION
**Pull request by wongband**
resolve #531

### CODE REVIEW

**Comment by jSylvestre** [comment]
@wongband  I don't know if you can fix or if this would be a @cydoval thing, but these get chopped once you select longer text

image

**Review by jSylvestre — CHANGES_REQUESTED** [review]
This should be about 60%:
image

But I don't see it when I do <75%
image

**Comment by wongband** [comment]
@jSylvestre Sorry about that, it should be ">75". I will fix it right now

**Review by jSylvestre — APPROVED** [review]

**Review by srkirkland — APPROVED** [review]
code looks good

**Pull request merged**
