### PR TITLE
Removed old files in ProjectDetailsContainer

### PR DESCRIPTION
**Pull request by wongband**

### CODE REVIEW

**Comment by jSylvestre** [comment]
Haven't tested it yet, but does this work correctly if the select more than 1 attachment at a time?

**Comment by srkirkland** [comment]
> Haven't tested it yet, but does this work correctly if the select more than 1 attachment at a time?

I have the same question given the `f[f.length-1]` portion

**Comment by wongband** [comment]
Sorry about that I will test that out right now for multiple attachments

**Review by jSylvestre — CHANGES_REQUESTED** [review]
Looks like you didn't save both attachments:

Selected 2 files:
image

Then, refresh the page:
image

**Comment by jSylvestre** [comment]
@wongband FYI, I'm not saying this is the best way to do it, but this is how I added multiple attachments for tickets server side:
https://github.com/ucdavis/Harvest/blob/main/Harvest.Web/Controllers/Api/TicketController.cs#L173

**Comment by wongband** [comment]
@jSylvestre I will take a look at it and refactor

**Review by jSylvestre — CHANGES_REQUESTED** [review]
After you have uploaded your files to request\files you need to clear out newFiles (I think)
Otherwise if you upload 2 files, then upload another file your model is passed 3 files instead of just the file that was newly selected.

**Review by jSylvestre — APPROVED** [review]
Works for me.

**Pull request merged**
