### PR TITLE
Added error checking for emtpy quantities in expenses

### LINKED ISSUE #80: Expenses with zero amounts
Either require an amount, or when the expenses are saved, skip ones that don't have a quantity

### PR DESCRIPTION
**Pull request by wongband**
resolve #80

### CODE REVIEW

**Review by srkirkland — CHANGES_REQUESTED** [review]
Since this is a list of expenses I don't think it'll do having a generic alert, we'll need to show the error associated with the row where the error is.  So perhaps each expense can keep track of it's validity and show the message.

**Comment by wongband** [comment]
Yea I can make it so that an error is displayed below the expense row.

**Review by jSylvestre — CHANGES_REQUESTED** [review]
Not working correctly.

image

**Review by jSylvestre — APPROVED** [review]
Minor issues can be fixed later.
🚢

**Pull request merged**
