### PR TITLE
Enable deleting activities

### PR DESCRIPTION
**Pull request by sprucely**
Double-checked, and quote totals are getting updated when an activity is deleted.

### CODE REVIEW

**Review by jSylvestre — APPROVED** [review]
Might be nice that if all the stuff in an activity is removed, that the activity gets removed when it saves. Or error validation.

**Review by srkirkland — APPROVED** [review]

**Comment by sprucely** [comment]
@srkirkland @jSylvestre Do you see any issues with my latest commit?

**Comment by srkirkland** [comment]
@sprucely What is the point of the clone? Just in case the save fails?  I think the idea of removing 0 valued stuff is fine but I'm not sure the point of the rest.

**Comment by sprucely** [comment]
Yeah, I don't like modifying state just before an operation that can fail.

**Comment by sprucely** [comment]
I also like cloning state that might be modified in a modal that can be cancelled.

**Comment by srkirkland** [comment]
If we are just changing the location on save (and really should just do a react router redirect in the future, why save the state at all? We are just going to immediately dispose the component.

**Comment by sprucely** [comment]
I thought the window.location thing might be replaced with something that holds on to the state.

**Comment by sprucely** [comment]
Do you want me to remove the clone stuff?

**Comment by srkirkland** [comment]
I don't think so. It'll be replaced but the state shouldn't be retained since it'll be a different route and this should swap out the top level component and remove the state long with everything else in the component.

**Comment by srkirkland** [comment]
> Do you want me to remove the clone stuff?

Yea. I think it was nice and clean before and we should leave it like that for now.

**Pull request merged**
