### PR TITLE
Added FileUpload and displayed attachments to ProjectDetailContainer

### LINKED ISSUE #257: hook up attachments on project page.
on the project details page, ex /project/details/28, hook up the attachments section to show the actual attachments associated with the project.  Also add in the fileUpload.tsx file so they can upload new files just like how it works on the new request page.  If a new file is upload it should show up in the list.

### PR DESCRIPTION
**Pull request by wongband**
resolve #257

### CODE REVIEW

**Review by jSylvestre — CHANGES_REQUESTED** [review]
I'm not seeing the attachments I created in the original request.

**Review by jSylvestre — CHANGES_REQUESTED** [review]
Now you need to save the newly uploaded files on the project details page to the database.
Simplest way would be to add a new submit button to that page and an endpoint to add the attachments.
The other thing that might be nicer is to detect when the file(s) has been uploaded, then automatically call a new endpoint to add it to the DB.

**Comment by wongband** [comment]
@jSylvestre I updated it so that it updates automatically whenever a new file is uploaded

**Review by jSylvestre — APPROVED** [review]
Looks ok to me, but wait for @srkirkland before merging.

And just a FYI, should the files that have already been uploaded show up here?
image

**Review by srkirkland — APPROVED** [review]
Code looks good.   Your formatting seems to be kinda strange.  Are you using `prettier` and is it configured to use the version of prettier in the clientApp folder?  Is there some other formatting extension you are using?

**Comment by wongband** [comment]
@srkirkland I think I am using the prettier config. I will double check

**Pull request merged**
